# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(757, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.papka = QtWidgets.QPushButton(self.centralwidget)
        self.papka.setGeometry(QtCore.QRect(20, 10, 111, 41))
        self.papka.setObjectName("papka")
        self.dgerkal = QtWidgets.QPushButton(self.centralwidget)
        self.dgerkal.setGeometry(QtCore.QRect(420, 500, 75, 23))
        self.dgerkal.setObjectName("dgerkal")
        self.nega = QtWidgets.QPushButton(self.centralwidget)
        self.nega.setGeometry(QtCore.QRect(640, 500, 75, 23))
        self.nega.setObjectName("nega")
        self.Rait = QtWidgets.QPushButton(self.centralwidget)
        self.Rait.setGeometry(QtCore.QRect(300, 500, 75, 23))
        self.Rait.setObjectName("Rait")
        self.pigkist = QtWidgets.QPushButton(self.centralwidget)
        self.pigkist.setGeometry(QtCore.QRect(530, 500, 75, 23))
        self.pigkist.setObjectName("pigkist")
        self.left = QtWidgets.QPushButton(self.centralwidget)
        self.left.setGeometry(QtCore.QRect(170, 500, 75, 23))
        self.left.setObjectName("left")
        self.zamitka = QtWidgets.QListWidget(self.centralwidget)
        self.zamitka.setGeometry(QtCore.QRect(10, 60, 141, 491))
        self.zamitka.setObjectName("zamitka")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 0, 581, 491))
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 757, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.papka.setText(_translate("MainWindow", "Папка"))
        self.dgerkal.setText(_translate("MainWindow", "Дзеркально"))
        self.nega.setText(_translate("MainWindow", "Ч/Б"))
        self.Rait.setText(_translate("MainWindow", "Праворуч"))
        self.pigkist.setText(_translate("MainWindow", "Різкість"))
        self.left.setText(_translate("MainWindow", "Ліворуч"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
